import os
import sqlite3
import json
import streamlit as st
import pandas as pd
import plotly.express as px

from dotenv import load_dotenv
load_dotenv()
gemini_api_key = os.getenv("GEMINI_API_KEY")

DB_PATH = os.path.join(os.path.dirname(__file__),'Smartviz.db')

st.set_page_config(page_title="SmartViz AI Analytics",page_icon="📊",layout="wide")

st.markdown("""
            <style>
            .main { background-color: #0f172a; color: #f8fafc; }
            .stButton>button { width: 100%; border-radius: 10px; background-color: #2563eb; color: white; border:none; }
            .stTextInput>div>div>input { background-color: #1e293b; color: white; border: 1px solid #334155; }
            div[data-testid="stMetricValue"] { color: #3b82f6; }
            </style>
            """,unsafe_allow_html=True)

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model = "gemini-2.5-flash",api_key = gemini_api_key,temperature=0.0)

from typing import Annotated,TypedDict,Sequence
from langchain_core.messages import BaseMessage,HumanMessage,AIMessage,SystemMessage
from langgraph.graph.message import add_messages
from langchain_core.tools import tool
from langgraph.graph import StateGraph,END

# Tool definition
@tool
def sql_query(query:str)->str:
    """
    Executes a read-only SQL query against the METRICS table in the Smartviz.db SQLite database.
    """
    conn = None
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute(query)
        results = cursor.fetchall()
        return str(results)
    except Exception as e:
        return f"Database Error:{e}"
    finally:
        if conn:
            conn.close()

# State definition
class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage],add_messages]
    query_result: str
    chart_config: dict

# Nodes
def run_query_agent(state: AgentState):
    """Node 1: Generates SQL. Includes specific instructions for column naming and comparisons."""
    system_prompt = (
        "You are an expert SQL generator for SQLite. The table is METRICS."
        "STRICT COLUMN NAMES (Use these exactly):"
        "- Value column: `_v_a_l_u_e_` (Always use CAST(_v_a_l_u_e_ as REAL))."
        "- Time column: `_s_t_a_r_t___t_i_m_e_` (FORMAT: 'YYYY-MM-DD HH:MM:SS.000 +0000')."
        "- Metric Name column: `_m_e_t_r_i_c___n_a_m_e_` (Note the triple underscores between words)."
        "RULES:"
        "1. Filter for Metric: 'Occupancy'."
        "2. Skip the header row: `WHERE _s_t_a_r_t___t_i_m_e_ != 'start_time'`."
        "3. For comparisons, use UNION ALL to retrieve results for both periods in one result set."
        )
    full_messages = [SystemMessage(content=system_prompt)] + list(state["messages"])
    query_agent = llm.bind_tools([sql_query])
    result = query_agent.invoke(full_messages)
    return {"messages":[result]}

def execute_sql(state: AgentState):
    """Node 2: Executes the tool call generated by the query agent."""
    last_message = state["messages"][-1]
    if not last_message.tool_calls:
        return state
    query = last_message.tool_calls[0]["args"]["query"]
    print(f"\n[SQL generated]:{query}")
    raw_result = sql_query.invoke(query)
    print(f"\n[Raw result]:{raw_result}")
    return {"query_result":raw_result}

def run_visualization_agent(state: AgentState):
    """Translates DB results into a JSON configuration for a chart."""
    if not state["query_result"] or "Database Error" in state["query_result"] or state["query_result"] == "[]":
        return {"chart_config": {"type":"none"}}
    vis_prompt = (
        f"Data from Database: {state['query_result']}\n"
        f"User Question: {state['messages'][0].content}\n"
        "Create a chart plan. Return ONLY a raw JSON object string with no backticks:"
        '{"type": "bar", "title": "Comparison", "labels": ["A","B"], "values": [10,20]}'
    )
    try:
        response = llm.invoke(vis_prompt)
        content = response.content.strip()
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].split("```")[0].strip()
        config = json.loads(content)
        print(f"[CHART JSON]: {json.dumps(config,indent=2)}")
        return {"chart_config": config}
    except Exception as e:
        print(f"Visualization Error: {e}")
        return {"chart_config": {"type": "none"}}

def run_analysis_agent(state: AgentState):
    """Node 4: Provides a natural language explanation, referencing the chart if it exists."""
    msg = f"Data: {state['query_result']}\nQuestion: {state['messages'][0].content}\n"
    if state["chart_config"].get("type") != "none":
        msg += f"(Note: A {state['chart_config']['type']} chart has been prepared.)"
    analysis_message = llm.invoke(msg)
    return {"messages": [analysis_message]}

# Router
def router(state: AgentState):
    """Decides the path of the workflow."""
    if state.get("query_result"):
        return "visualize"
    if state["messages"][-1].tool_calls:
        return "execute_sql"
    return END     

# Graph
workflow = StateGraph(AgentState)
workflow.add_node("query_agent",run_query_agent)
workflow.add_node("execute_sql",execute_sql)
workflow.add_node("visualize",run_visualization_agent)
workflow.add_node("analyze",run_analysis_agent)
workflow.set_entry_point("query_agent")
workflow.add_conditional_edges("query_agent",router,{"execute_sql": "execute_sql", END:END})
workflow.add_edge("execute_sql","visualize")
workflow.add_edge("visualize","analyze")
workflow.add_edge("analyze",END)
app_engine = workflow.compile()

# Streamlit UI
st.title("📊 Smartviz Occupancy Analytics")
st.markdown("### Dissertation Prototype: LLM-Driven Spatial Data Analysis")

# Sidebar for Experimentation
with st.sidebar:
    st.header("🧪 Question Sandbox")
    st.write("Quickly test these research questions:")
    
    sample_q1 = "What was the total occupancy on 2025-03-01?"
    sample_q2 = "Compare occupancy between 09:00 and 17:00 for 2025-03-02."
    sample_q3 = "Which hour had the peak occupancy on 2025-03-01?"
    
    selected_q = None
    if st.button(sample_q1): selected_q = sample_q1
    if st.button(sample_q2): selected_q = sample_q2
    if st.button(sample_q3): selected_q = sample_q3
    
    st.divider()
    st.header("App Settings")
    st.info("This agent uses LangGraph and Gemini 2.5 Flash to analyze occupancy patterns.")
    if st.button("Clear Dashboard"):
        st.rerun()

# User Input
input_val = selected_q if selected_q else ""
user_query = st.text_input("Ask a question about the occupancy data:", 
                          value=input_val,
                          placeholder="e.g., Compare morning occupancy of 2025-03-01 and 2025-03-02")

if user_query:
    with st.spinner("Agent is thinking and querying the database..."):
        # Run the Graph
        initial_state = {"messages": [HumanMessage(content=user_query)], "query_result": "", "chart_config": {}}
        final_output = app_engine.invoke(initial_state)
        
        # Extract results
        answer = final_output['messages'][-1].content
        chart_data = final_output['chart_config']
        
        # Display Analysis
        st.subheader("Analysis Results")
        st.write(answer)
        
        # Display Visualization
        if chart_data.get("type") != "none":
            st.divider()
            col1, col2 = st.columns([2, 1])
            
            with col1:
                st.subheader(chart_data.get("title", "Data Visualization"))
                df = pd.DataFrame({
                    "Category": chart_data["labels"],
                    "Value": chart_data["values"]
                })
                
                if chart_data["type"] == "bar":
                    fig = px.bar(df, x="Category", y="Value", color="Category", 
                                 template="plotly_dark", color_discrete_sequence=px.colors.qualitative.Pastel)
                    st.plotly_chart(fig, width='stretch')
                elif chart_data["type"] == "pie":
                    fig = px.pie(df, names="Category", values="Value", template="plotly_dark")
                    st.plotly_chart(fig, width='stretch')
            
            with col2:
                st.subheader("Key Metrics")
                total_val = sum(chart_data["values"])
                peak_val = max(chart_data["values"])
                st.metric("Total Occupancy", f"{total_val:,.2f}")
                st.metric("Peak Value", f"{peak_val:,.2f}")
        
            
